---
- hosts: all
  become: yes

  tasks:

    # tasks file for install Java 1.8.0 to Debian systems
    - name: apt-get update
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install latest version of "openjdk-8-jdk" ignoring "install-recommends"
      apt:
        name: openjdk-8-jdk
        state: latest
        install_recommends: no

    - name: Just force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Install unzip
      apt:
        name: unzip
        state: latest
        install_recommends: no

    - name: Create a /SAP directory if it does not exist
      file:
        path: /SAP
        state: directory
        mode: '0755'

    - name: Copying all files from ./files_to_copying/ to remote /SAP
      unarchive:
        src: "{{item}}"
        dest: /SAP
      with_fileglob:
        - ./files_to_copying/*



#    # Next Play : install jenkins Role
#- hosts: all
#  become: yes
#
#  roles:
#    - { role: geerlingguy.jenkins, when: ansible_system == 'Linux' }

